---
title: "Processing inclusion population data and polynomial fitting"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup}
library(ggplot2)
library(dplyr)
```

## Load the data
```{r load}
radius <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/radius.csv", na = "NA")

area <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/area.csv", na = "NA")

volume <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/volume.csv", na = "NA")
```

## For all datasets, calculate average and SEM of all inclusions at each timepoint 
```{r average}

radius_avg <- rowMeans(radius[,-1], na.rm = TRUE)

# apply the sem function across rows excluding the 1st column
radius_sem <- apply(radius[,-1], 1, function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
                                                 
area_avg <- rowMeans(area[,-1], na.rm = TRUE) 
#area_avg <- cbind(time = c(0:6), area = area_avg) # add a time column so that we can fit the f
area_sem <- apply(area[,-1], 1,
                  function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
                                  
volume_avg <- rowMeans(volume[,-1], na.rm = TRUE)
volume_sem <- apply(volume[,-1], 1, function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
```

## Fit the data to specified functions

```{r fits, echo=FALSE}

# This is the time column that we will use for all fits except area
times <- (0:6)

# Fit radius to a straight line
fit_radius_line <- lm(radius_avg ~ I(times))

# Alternate fits for radius
fit_radius_onehalf <- lm(radius_avg ~ I(times^0.5))
fit_radius_onethird <- lm(radius_avg ~ I(times^0.33))

# Display R2
paste("radius fit with line, adj. R2:", summary(fit_radius_line)$adj.r.squared)
paste("radius fit to t^1/2:", summary(fit_radius_onehalf)$adj.r.squared)
paste("radius fit to t^1/3:", summary(fit_radius_onethird)$adj.r.squared)


# Fit area to ax2 +bx + c with b = 0 
# omit last point
area_times <- (0:5)
area_avg <- area_avg[1:6]
area_sem <- area_sem[1:6]
fit_area_deg2 <- lm(area_avg ~ I(area_times^2))

# alternate fits and report for area
fit_area_line <- lm(area_avg ~ I(area_times))
fit_area_twothirds <- lm(area_avg ~ I(area_times^0.67))
paste("area fit with t^2, adj. R2:",summary(fit_area_deg2)$adj.r.squared)
paste("area fit with line, adj. R2:",summary(fit_area_line)$adj.r.squared)
paste("area fit with t^2/3, adj. R2:",summary(fit_area_twothirds)$adj.r.squared)


# Fit volume to ax3
fit_volume_deg3 <- lm(volume_avg ~ I(times^3))

# alternate fits and report for volume
fit_volume_threehalves <- lm(volume_avg ~ I(times^1.5))
fit_volume_line <- lm(volume_avg ~ I(times))
paste("volume fit with t^3, adj. R2:",summary(fit_volume_deg3)$adj.r.squared)
paste("volume fit with t^3/2, adj. R2:",summary(fit_volume_threehalves)$adj.r.squared)
paste("volume fit with line, adj. R2:",summary(fit_volume_line)$adj.r.squared)

```

## Generate predictions based on the preferred fits

```{r predictions}

# Generate predicted values for the graph

predict_radius <- as.data.frame(cbind(time = times, radius = predict(fit_radius_line, data.frame(x = times))))

predict_area <- as.data.frame(cbind(time = area_times, area = predict(fit_area_deg2, data.frame(x = area_times))))

predict_volume <- as.data.frame(cbind(time = times, volume = predict(fit_volume_deg3, data.frame(x = times))))


```

## Plot the data
```{r plot area}

# plot with error bars from sd

area_data <- as.data.frame(cbind(time = area_times, area = area_avg))
plot_area <- ggplot(data = area_data, aes(x = time, y = area)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = area_avg - area_sem, ymax = area_avg + area_sem)) +
  geom_line(color='red',data = predict_area, aes(x=time, y=area))

# for a fitted line add: + geom_smooth(method='lm', formula= y~x)

plot_area

```

