---
title: "Processing inclusion population data and polynomial fitting"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup}
library(ggplot2)
library(dplyr)
```

## Load the data (using a subset of the inclusions)
```{r load}
radius <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/data/radius subset2.csv", na = "NA")

# omit last row
radius <- radius[-nrow(radius),]

area <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/data/area subset2.csv", na = "NA")
area <- area[-nrow(area),]

volume <- read.csv("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/data/volume subset2.csv", na = "NA")
volume <- volume[-nrow(volume),]

```

## For all datasets, calculate average and SEM of all inclusions at each timepoint 
```{r average}

# omitting the first column as it is the time
radius_avg <- rowMeans(radius[,-1], na.rm = TRUE)

# apply the sem function across rows excluding the 1st column
radius_sem <- apply(radius[,-1], 1, function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
                                                 
area_avg <- rowMeans(area[,-1], na.rm = TRUE) 
area_sem <- apply(area[,-1], 1,
                  function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
                                  
volume_avg <- rowMeans(volume[,-1], na.rm = TRUE)
volume_sem <- apply(volume[,-1], 1, function(x) (sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))))
```

## Fit the data to specified functions

```{r fits, echo=FALSE}

# This is the time column that we will use for all fits except area
times <- (0:5)

# Fit radius to a straight line
fit_radius_line <- lm(radius_avg ~ I(times))

# Alternate fits for radius
fit_radius_onehalf <- lm(radius_avg ~ I(times^0.5))
fit_radius_onethird <- lm(radius_avg ~ I(times^0.33))

# Display R2
paste("radius fit with line, adj. R2:", summary(fit_radius_line)$adj.r.squared)
paste("radius fit to t^1/2:", summary(fit_radius_onehalf)$adj.r.squared)
paste("radius fit to t^1/3:", summary(fit_radius_onethird)$adj.r.squared)


# Fit area to ax2 +bx + c with b = 0 
area_avg <- area_avg[1:6]
area_sem <- area_sem[1:6]
fit_area_deg2 <- lm(area_avg ~ I(times^2))

# alternate fits and report for area
fit_area_line <- lm(area_avg ~ I(times))
fit_area_twothirds <- lm(area_avg ~ I(times^0.67))
paste("area fit with t^2, adj. R2:",summary(fit_area_deg2)$adj.r.squared)
paste("area fit with line, adj. R2:",summary(fit_area_line)$adj.r.squared)
paste("area fit with t^2/3, adj. R2:",summary(fit_area_twothirds)$adj.r.squared)


# Fit volume to ax3
fit_volume_deg3 <- lm(volume_avg ~ I(times^3))

# alternate fits and report for volume
fit_volume_threehalves <- lm(volume_avg ~ I(times^1.5))
fit_volume_line <- lm(volume_avg ~ I(times))
paste("volume fit with t^3, adj. R2:",summary(fit_volume_deg3)$adj.r.squared)
paste("volume fit with t^3/2, adj. R2:",summary(fit_volume_threehalves)$adj.r.squared)
paste("volume fit with line, adj. R2:",summary(fit_volume_line)$adj.r.squared)

```

## Generate predictions based on the preferred fits

```{r predictions}

# Generate predicted values for the graph

predict_radius <- as.data.frame(cbind(time = times, radius = predict(fit_radius_line, data.frame(x = times))))

predict_area <- as.data.frame(cbind(time = times, area = predict(fit_area_deg2, data.frame(x = times))))

predict_volume <- as.data.frame(cbind(time = times, volume = predict(fit_volume_deg3, data.frame(x = times))))


```

## Plot the data with predictions
```{r plot}

# radius 

# plot with prediction (fitted curve) and error bars from SEM
radius_data <- as.data.frame(cbind(Time = times, Radius = radius_avg))
plot_radius <- ggplot(data = radius_data, aes(x = Time, y = Radius)) +
  theme_classic() +
  geom_point(size = 1) +
  coord_cartesian(ylim = c(0,0.6)) +
  geom_errorbar(aes(ymin = radius_avg - radius_sem, ymax = radius_avg + radius_sem),
                width = 0.1) +
  geom_line(color='black',data = predict_radius, aes(x=time, y=radius))

# show the plot 
plot_radius

# export the plot
ggsave("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/plots/radius_subset2_plot.pdf", plot = plot_radius,device = pdf(),width = 4, height = 3, units = "in",dpi = 600)

# area 

# plot with prediction (fitted curve) and error bars from SEM
area_data <- as.data.frame(cbind(Time = times, Area = area_avg))
plot_area <- ggplot(data = area_data, aes(x = Time, y = Area)) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = area_avg - area_sem, ymax = area_avg + area_sem),
                width = 0.1) +
  geom_line(color='black',data = predict_area, aes(x=time, y=area))

# show the plot 
plot_area

# export the plot
ggsave("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/plots/area_subset2_plot.pdf", plot = plot_area,device = pdf(),width = 4, height = 3, units = "in",dpi = 600)

# volume

# plot with prediction (fitted curve) and error bars from SEM
volume_data <- as.data.frame(cbind(Time = times, Volume = volume_avg))
plot_volume <- ggplot(data = volume_data, aes(x = Time, y = Volume)) +
  theme_classic() +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = volume_avg - volume_sem, ymax = volume_avg + volume_sem),
                width = 0.1) +
  geom_line(color='black',data = predict_volume, aes(x=time, y=volume))

# show the plot 
plot_volume

# export the plot
ggsave("/Users/theresaswayne/Documents/GitHub/data-analysis/R/LRRE_Htt_fit/plots/volume_subset2_plot.pdf", plot = plot_volume,device = pdf(),width = 4, height = 3, units = "in",dpi = 600)
```

