# R script to calculate active scan time from Cytation BioSpa log
# Theresa Swayne, 2020
# Reads a txt file generated by the BioSpa from the hlog file (not the audit trail)
# 
# Date and time use the default Gen5 format.

# works with warnings but does not handle multiple reads.

# ---- Setup ----

library(tidyverse) # for reading and parsing
library(readr)
library(tcltk) # for file choosing
library(tools) # for file paths

# ---- User chooses the input file ----

# use tk_choose to get a message in the chooser window

logfile <- tk_choose.files(default = "", caption = "Select the BioSpa log file", multi = FALSE) 

# read the data -- parsing errors may occur but data should be read ok.

logdata <- read_delim(logfile, 
                          "\t", escape_double = FALSE, col_names = FALSE, 
                          col_types = cols(X2 = col_character()), 
                          trim_ws = TRUE)
filedate <-  file_path_sans_ext(basename(logfile)) # in character format

# ---- Find start and end times ----
# 
# # remove duplicate lines logged during discontinuous kinetic procedures
# 
# logdata_unique <- unique(logdata)
# 
# # add a column for the Read number to help with merging the data later 
# 
# startTimes <- logdata_unique %>% 
#   filter(grepl("started", Event)) %>%
#   select(Start = Date)  %>%
#   mutate(Read = row_number())
# 
# endTimes <- logdata_unique %>% 
#   filter(grepl("completed", Event)) %>%
#   select(End = Date)  %>%
#   mutate(Read = row_number())
# 
# 
# # combine start and end times so that each row represents a single read step
# 
# scanTimes <- full_join(startTimes, endTimes, by = "Read") # combine using original read number
# 
# # ---- Calculate elapsed time and save ----
# 
# scanTimes <- scanTimes %>% 
#   mutate(elapsedTime = difftime(End, Start, units = "hours")) # convert elapsedTime to hours
# 
# # filter out NAs that arise from aborted runs
# # calculate active time for whole expt
# 
# scanTimeTotal <-  scanTimes %>%
#   filter(is.na(elapsedTime) == FALSE) %>%
#   summarise(TotalHours = sum(elapsedTime)) 
# 
# # save results in the same directory 
# 
# logName <- basename(logfile) # name of the file without higher levels
# 
# parentDir <- dirname(logfile) # parent of the logfile
# 
# outputFile = paste(Sys.Date(), logName, "_total.csv") # spaces will be inserted
# 
# write_csv(scanTimeTotal,file.path(parentDir, outputFile))

