# R script to calculate active scan time from Cytation BioSpa log
# Theresa Swayne, 2020
# Reads a single tab-delimited txt file generated by the BioSpa from the hlog file (not the audit trail)
# 

# ---- Setup ----

library(tidyverse) # for reading and parsing
library(readr) # for reading and parsing
library(tcltk) # for file choosing
library(tools) # for file paths

# ---- Manually choose input file ----

# tk_choose allows us to put a message in the chooser window

logfile <- tk_choose.files(default = "", caption = "Select the BioSpa log file", multi = FALSE)

# capture the date of the logfile, which is the base filename in YYYY-MM-DD format

logDate <-  file_path_sans_ext(basename(logfile)) # in character format

# read the data

logdata <- read_delim(logfile, 
                          "\t", escape_double = FALSE, 
                          col_names = c("Row","Timestamp","Notes"), 
                          col_types = cols(Timestamp = col_character()), 
                          trim_ws = TRUE)

# --- Make the timestamp column into a proper date and time ---

# remove the day of the week (1st 5 chars)
logdata$Timestamp <- substr(logdata$Timestamp,5,nchar(logdata$Timestamp))

# add the date from the filename, and a space
logdata$Timestamp <- (sub("^", paste(logDate, " "), logdata$Timestamp))

# translate the column into POSIXct time format
logdata$Timestamp <- as.POSIXct(logdata$Timestamp, format = '%Y_%m_%d %H:%M:%S')

# TEST if time is accurately calculated
# double brackets retrieve values rather than 1x1 tibbles

testtime <- as.numeric(difftime(logdata[[2,2]], logdata[[1,2]], units = "hours"))

# TODO Filter for begun and completed rows

imagingTimes <- logdata %>% 
  filter(grepl("has begun|has completed", Notes))


# TODO Get plate number into a column
# TODO Get protocol into a column 
# TODO Get imaging run number into a column

# startTimes <- logdata_unique %>% 
#   filter(grepl("started", Event)) %>%
#   select(Start = Date)  %>%
#   mutate(Read = row_number())
# 
# endTimes <- logdata_unique %>% 
#   filter(grepl("completed", Event)) %>%
#   select(End = Date)  %>%
#   mutate(Read = row_number())

# TODO Calculate difftime for each run
# TODO Sum imaging times per protocol and plate (note 2 plates can run same protocol and 2 users may use the sample plate pos in a day)


# startTimes <- logdata_unique %>% 
#   filter(grepl("started", Event)) %>%
#   select(Start = Date)  %>%
#   mutate(Read = row_number())
# 
# endTimes <- logdata_unique %>% 
#   filter(grepl("completed", Event)) %>%
#   select(End = Date)  %>%
#   mutate(Read = row_number())
# 
# 
# # combine start and end times so that each row represents a single read step
# 
# scanTimes <- full_join(startTimes, endTimes, by = "Read") # combine using original read number
# 
# # ---- Calculate elapsed time and save ----
# 
# scanTimes <- scanTimes %>% 
#   mutate(elapsedTime = difftime(End, Start, units = "hours")) # convert elapsedTime to hours
# 
# # filter out NAs that arise from aborted runs
# # calculate active time for whole expt
# 
# scanTimeTotal <-  scanTimes %>%
#   filter(is.na(elapsedTime) == FALSE) %>%
#   summarise(TotalHours = sum(elapsedTime)) 
# 
# # save results in the same directory 
# 
# logName <- basename(logfile) # name of the file without higher levels
# 
# parentDir <- dirname(logfile) # parent of the logfile
# 
# outputFile = paste(Sys.Date(), logName, "_total.csv") # spaces will be inserted
# 
# write_csv(scanTimeTotal,file.path(parentDir, outputFile))

