# MEN_analysis_drawnROI_2.R
# collect and report data on mito localization expts
# designed for 2019-01-18 data

# REQUIRES a dataframe or tibble called df generated by combine_volocity_files_drawnROI.R
# REQUIRES the original filenames to contain info on temp and threshold
# REQUIRES the correct voxel size to be entered below

# TODO: reduce the number of data frames by gradually adding to a single output table
# TODO: Add n to the labels for the plots (for each group)

# Setup -----
require(tidyverse)
require(here)
voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3


# TODO: for future analyses get a background ROI from the file. (How to choose? Make sure it's always larger than the cells?)

# Get extracellular background from additional file -----

# TODO: update to allow user to select file

# ENTER BACKGROUND FILENAME HERE ---
subfolder <- "2019-01-18 analysis HK"
inputFolder <- here(file.path("data",subfolder))
bkgdfile <- "Extracellular Background GFP channel.csv"

xcell_bg <- read_csv(file.path(inputFolder, bkgdfile),
                          locale = locale(encoding = "latin1")) %>%
  select(ItemName, ExtracellularBackground) # omit crazy other column


# check background distribution
boxplot(xcell_bg[,2], main = "Deconvolved green extracellular background")
hist(xcell_bg[,2] %>% unlist, main="Deconvolved green extracellular background")


# Summarize mito values -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

# NOTE: Cannot count on Voxel Count. 

all_mito <- df %>% filter(Population == "Mito") %>%
  group_by(filename) # mitos in a cell are grouped

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntDen = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            RawMitoMean = sum(`Mean (roGFP 470 (DCI: 60 its, roGFP 470))`*`Volume (µm³)`)/sum(`Volume (µm³)`),
            MitoVolume_um3 = sum(`Volume (µm³)`),
            MitoVoxelCount = sum(`Voxel Count`), # may not be present
            ItemName = first(`Item Name`)) 


# Get whole-cell values -------

# uncorrected cell intden

# TODO: adapt for different type of background ROIs

raw_cell_intden <- df %>% filter(Population == "ROIs") %>% # cell and background ROIs
  group_by(filename) %>%
  filter(`Volume (µm³)` == max(`Volume (µm³)`)) %>% # take the larger ROI from each file 
  select(filename,
         RawCellIntDen = `Sum (roGFP 470 (DCI: 60 its, roGFP 470))`,
         RawCellMean = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellVolume_um3 = `Volume (µm³)`,
         CellVoxelCount = `Voxel Count`, # may not be present
         ItemName = `Item Name`)

# Collect columns for cell, mito, and background ------

cell_mito_intden <- raw_cell_intden %>% ungroup %>% 
  mutate(
  RawMitoIntDen = raw_mito_intden$RawMitoIntDen,
  RawMitoMean = raw_mito_intden$RawMitoMean,
  MitoVolume_um3 = raw_mito_intden$MitoVolume_um3,
  MitoVoxelCount = raw_mito_intden$MitoVoxelCount)

cell_mito_xc_bkd <- cell_mito_intden %>% left_join(xcell_bg) # only common column is ItemName

# Get fraction of green signal in mito ----

#   corr intden = (sum) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size µm3/pixel

bkgcorr <- function (rawmean, 
                     vol,
                     voxsize,
                     background) {
  # subtracts background from every voxel in a volume 
  # uses the mean rather than intden, in order to avoid truncation of sig figs by Volocity 
  (rawmean - background) * (vol/voxsize)
}

# correcting with extracellular bkgd -------

cell_corr <- bkgcorr(cell_mito_xc_bkd$RawCellMean,
                     cell_mito_xc_bkd$CellVolume_um3,
                     voxel_size,
                     cell_mito_xc_bkd$ExtracellularBackground)

mito_corr <- bkgcorr(cell_mito_xc_bkd$RawMitoMean,
                     cell_mito_xc_bkd$MitoVolume_um3,
                     voxel_size,
                     cell_mito_xc_bkd$ExtracellularBackground)

frac_mito <- mito_corr/cell_corr
 
corrected_mito_loc_xc <- cell_mito_xc_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)

# Get weighted mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background
mito_mean_corr <- corrected_mito_loc_xc$RawMitoMean - corrected_mito_loc_xc$ExtracellularBackground

corrected_mito_loc_xc <- corrected_mito_loc_xc %>% mutate(MitoMeanCorr = mito_mean_corr)


# Compare results by temperature and threshold offset ------

# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc_xc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc_xc$filename, temp_exp)

corrected_mito_loc_xc <- corrected_mito_loc_xc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])

# all data by temp

boxplot(corrected_mito_loc_xc$FractionInMito ~ corrected_mito_loc_xc$Temp, main = "Fraction of GFP integrated density in mitochondria, GTY030") # whiskers extend to 1.5x interquartile range

boxplot(corrected_mito_loc_xc$MitoMeanCorr ~ corrected_mito_loc_xc$Temp, main = "Mean GFP intensity in mitochondria, GTY030")

# Compare total cell GFP across temperatures

# is total cellular GFP constant with temp?
boxplot(corrected_mito_loc_xc$CellIntDenCorr ~ corrected_mito_loc_xc$Temp, main = "Total corrected cell GFP, xc bkgd")

# cell intden vs volume
# plot(corrected_mito_loc_xc$CellIntDenCorr, corrected_mito_loc_xc$CellVolume_um3, main = "XC Bkgd")

boxplot(corrected_mito_loc_xc$FractionInMito ~ corrected_mito_loc_xc$MitoThresh, main = "Fraction of MEN in mito, by threshold offset")

# Statistical tests -----

permTfrac <- corrected_mito_loc_xc %>% 
  filter(Temp == 25) %>% 
  select(FractionInMito) %>%
  unlist

restrTfrac <- corrected_mito_loc_xc %>% 
  filter(Temp == 36) %>% 
  select(FractionInMito) %>%
  unlist

permTmean <- corrected_mito_loc_xc %>% 
  filter(Temp == 25) %>% 
  select(MitoMeanCorr) %>%
  unlist

restrTmean <- corrected_mito_loc_xc %>% 
  filter(Temp == 36) %>% 
  select(MitoMeanCorr) %>%
  unlist

# are data normally distributed?

hist(permTfrac)
qqnorm(permTfrac, main = "Fraction of MEN in mito, 25C")
permTfrac_shapiro <- shapiro.test(permTfrac)$p.value # low p value (< 0.05 by convention) means not normal

hist(restrTfrac)
qqnorm(restrTfrac, main = "Fraction of MEN in mito, 36C")
restrTfrac_shapiro <- shapiro.test(restrTfrac)$p.value

hist(permTmean)
qqnorm(permTmean, main = "Mean of MEN in mito, 25C")
permTmean_shapiro <- shapiro.test(permTmean)$p.value

hist(restrTmean, breaks = 50)
qqnorm(restrTmean, main = "Mean of MEN in mito, 36C")
restrTmean_shapiro <- shapiro.test(restrTmean)$p.value

# comparison with true normal data
testdata <- rnorm(1000)
hist(testdata)
qqnorm(testdata)
testdata_shapiro <- shapiro.test(testdata)$p.value

wilcoxon_frac <- wilcox.test(permTfrac, restrTfrac)$p.value
wilcoxon_mean <- wilcox.test(permTmean, restrTmean)$p.value

mean_25_frac <- mean(permTfrac)
mean_36_frac <- mean(restrTfrac)
mean_25_mean <- mean(permTmean)
mean_36_mean <- mean(restrTmean)

# do not use t-test for non-normally distributed data
# frac_t <- t.test(permTfrac, restrTfrac)
# mean_t <- t.test(permTmean, restrTmean)

# Save csv table ------
# overwrites without warning!

outputFile2 = paste(Sys.Date(), "mito_loc_xc.csv") # spaces will be inserted

# write_csv(corrected_mito_loc_xc, file.path(here("data"), subfolder, outputFile2))

