# MEN_analysis_2.R
# collect and report data on mito localization expts

# REQUIRES a dataframe or tibble called df generated by combine_volocity_files.R
# REQUIRES the original filenames to contain info on temp and threshold
# REQUIRES the correct voxel size to be entered below

# Setup -----
require(tidyverse)
require(here)


# Get background values ---------
# Each file should have exactly 1 background ROI.
# (filter for Population == ROIs, select filename, 470DCI columns)

green_bg <- filter(df, Population == "ROIs") %>%
  select(filename, MeanBackground = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`)


# simple plots
# Most background levels are 650-690
boxplot(green_bg[,2], main = "Deconvolved green channel background")
hist(green_bg[,2] %>% unlist, main="Deconvolved green channel background")


# Summarize mito values -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

all_mito <- df %>% filter(Population == "Mito") %>% 
  drop_na(`Compartment Whole cells ID`) %>%        # eliminate mitos not belonging to a cell
  group_by(filename, `Compartment Whole cells ID`) # will sum first by cell

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntden = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            MitoVolume_um3 = sum(`Volume (µm³)`))

  # result has 4 columns

# Get whole cell values -------

# uncorrected cell intden, omitting cells with no mito 
raw_cell_intden <- filter(df,
                          Population == "Whole cells" & `Number of contained Mito` != 0) %>%
  select(filename,
         ID,
         RawCellIntDen = `Sum (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellVolume_um3 = `Volume (µm³)`)

# Add columns for mito sum, volume, and background ROI ------

cell_mito_intden <- raw_cell_intden %>% mutate(
  RawMitoIntden = raw_mito_intden$RawMitoIntden,
  MitoVolume_um3 = raw_mito_intden$MitoVolume_um3)

  # note: can insert RawMitoCellID = raw_mito_intden$`Compartment Whole cells ID` to verify that IDs are correct

cell_mito_bkd <- cell_mito_intden %>% left_join(green_bg) # only common column is filename

# Determine fraction of green signal in mito ----

#   corr intden = (sum) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size µm3/pixel

voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3

bkgcorr <- function (rawintden, 
                     vol,
                     background,
                     voxsize) {
  # subtracts background from every voxel in a volume 
  rawintden - (background * (vol/voxsize))
}

cell_corr <- bkgcorr(cell_mito_bkd$RawCellIntDen,
                     cell_mito_bkd$CellVolume_um3,
                     cell_mito_bkd$MeanBackground,
                     voxel_size)

mito_corr <- bkgcorr(cell_mito_bkd$RawMitoIntden,
                     cell_mito_bkd$MitoVolume_um3,
                     cell_mito_bkd$MeanBackground,
                     voxel_size)

frac_mito <- mito_corr/cell_corr

corrected_mito_loc <- cell_mito_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)


# Determine weighted mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background


mean_per_cell <- function (rawintden, 
                           vol,
                           background,
                           voxsize) {
  # determines mean intensity per voxel and subtracts background 
  (rawintden * voxsize/vol) - background # return value
}

mito_mean_corr <- mean_per_cell(corrected_mito_loc$RawMitoIntden,
                                corrected_mito_loc$MitoVolume_um3,
                                corrected_mito_loc$MeanBackground,
                                voxel_size)


corrected_mito_loc <- corrected_mito_loc %>% mutate(MitoMeanCorr = mito_mean_corr)



# Compare results by temperature and threshold offset ------

# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc$filename, temp_exp)

corrected_mito_loc <- corrected_mito_loc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])


# all data by temp
boxplot(corrected_mito_loc$FractionInMito ~ corrected_mito_loc$Temp, main = "All mito threshold offsets")

# effect of mito threshold (confounded with temp)
boxplot(corrected_mito_loc$FractionInMito ~ corrected_mito_loc$MitoThresh, main = "Fraction of MEN in mito, by threshold offset")

mito50 <- corrected_mito_loc %>% filter(MitoThresh == "-50")
mito80 <- corrected_mito_loc %>% filter(MitoThresh == "-80")

boxplot(mito50$FractionInMito ~ mito50$Temp, main = "Frac MEN in mito, threshold offset -50")
boxplot(mito80$FractionInMito ~ mito80$Temp, main = "Frac MEN in mito, threshold offset -80")

# frac/mito values tend to be higher with -80 offset, volumes tend to be higher and much more variable (n=60)

boxplot(mito50$MitoVolume_um3 ~ mito50$Temp, main = "Volume, Mito threshold offset -50", ylim = c(0,70))
boxplot(mito80$MitoVolume_um3 ~ mito80$Temp, main = "Volume, Mito threshold offset -80", ylim = c(0,70))

# for intden, thresh of -80 seems to show more of a diff but there are too few cells (8) in the 36C category and some of them have much higher mito volume

# for mean, thresh of -50 shows more diff

boxplot(mito50$MitoMeanCorr ~ mito50$Temp, main = "Mean GFP in mito, Mito threshold offset -50")
boxplot(mito80$MitoMeanCorr ~ mito80$Temp, main = "Mean GFP in mito, Mito threshold offset -80")

boxplot(corrected_mito_loc$MitoMeanCorr ~ corrected_mito_loc$Temp, main = "Mean corrected mito GFP, all threshold offsets")


# Compare total cell GFP across temperatures

boxplot(corrected_mito_loc$CellIntDenCorr ~ corrected_mito_loc$Temp, main = "Total corrected cell GFP, all threshold offsets")


# TODO: reduce the number of data frames by gradually adding to a single output table

# TODO: Add n to the labels for the plots (for each group)

# Save csv table ------
# overwrites without warning!

outputFile = paste(Sys.Date(), "mito_loc.csv") # spaces will be inserted
write_csv(corrected_mito_loc, file.path(here("data"), outputFile))
