# MEN_analysis.R
# collect data on mito localization expts

# Requires a dataframe called df generated by combine_volocity_files.R

# Setup -----
require(dplyr)
require(here)
require(ggplot2)


# Background comparison ------
# filter for rows where Population = ROI and select the mean of 470 DCI

green_bg <- filter(df, Population == "ROIs") %>%
  select("Mean (roGFP 470 (DCI: 60 its, roGFP 470))") %>%
  unlist

# simple boxplot
boxplot(green_bg)
hist(green_bg, breaks = 13)
# most background is a little under 700, but 2 are near 800

# Mito localization of MEN proteins -----

# group by cell 

# for each cell calculate in green DCI channel:
#   get background (ROIs column)
#   mito intden = (sum of mito Sums) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size L x W x D
#   cell intden = Whole Cell Sum - (background * voxel count)
#   fxn in mito = mito intden/cell intden

# for all cells: tabulate all fxn in mito

# TODO: get voxel size (or in future, count) so we can subtract background from every pixel!

