# MEN_analysis_2.R
# collect and report data on mito localization expts

# REQUIRES a dataframe or tibble called df generated by combine_volocity_files_drawnROI.R
# REQUIRES the original filenames to contain info on temp and threshold
# REQUIRES the correct voxel size to be entered below

# Setup -----
require(tidyverse)
require(here)


# Get background values ---------
# NOTE these are intracellular background levels
# Each file has exactly 2 ROIs, the cell and the background.
# Background ROI is always smaller.

green_bg <- filter(df, Population == "ROIs") %>%
  group_by(filename) %>%
  filter(`Volume (µm³)` == min(`Volume (µm³)`)) %>% # take the smaller ROI from each file 
  select(filename, MeanBackground = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`) 

# additional background column
# Kludge alert 
# ENTER BACKGROUND FILENAME HERE ---
xcell_bg <-  X2019_01_15_extracellular_background
boxplot(xcell_bg[,2], main = "Deconvolved green extracellular background")
hist(xcell_bg[,2] %>% unlist, main="Deconvolved green extracellular background")


# simple plots
# For 1-15 data, most background levels are 580-620
boxplot(green_bg[,2], main = "Deconvolved green cytoplasmic background")
hist(green_bg[,2] %>% unlist, main="Deconvolved green cytoplasmic background")


# Summarize mito values -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

# TODO: Update for new data ------

all_mito <- df %>% filter(Population == "Mito") %>%
  group_by(filename) # mitos in a cell are grouped

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntDen = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            RawMitoMean = sum(`Mean (roGFP 470 (DCI: 60 its, roGFP 470))`*`Voxel Count`)/sum(`Voxel Count`),
            MitoVolume_um3 = sum(`Volume (µm³)`),
            MitoVoxelCount = sum(`Voxel Count`))


# Get whole cell values -------

# uncorrected cell intden
raw_cell_intden <- df %>% filter(Population == "ROIs") %>% # cell and background ROIs
  group_by(filename) %>%
  filter(`Volume (µm³)` == max(`Volume (µm³)`)) %>% # take the larger ROI from each file 
  select(filename,
         RawCellIntDen = `Sum (roGFP 470 (DCI: 60 its, roGFP 470))`,
         RawCellMean = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellVolume_um3 = `Volume (µm³)`,
         CellVoxelCount = `Voxel Count`)

# Collect columns for cell, mito, and background ------

cell_mito_intden <- raw_cell_intden %>% ungroup %>% 
  mutate(
  RawMitoIntDen = raw_mito_intden$RawMitoIntDen,
  RawMitoMean = raw_mito_intden$RawMitoMean,
  MitoVolume_um3 = raw_mito_intden$MitoVolume_um3,
  MitoVoxelCount = raw_mito_intden$MitoVoxelCount)

cell_mito_bkd <- cell_mito_intden %>% left_join(green_bg) # only common column is filename

cell_mito_xc_bkd <- cell_mito_intden %>% left_join(xcell_bg) # only common column is filename

# Get fraction of green signal in mito ----

#   corr intden = (sum) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size µm3/pixel

voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3

bkgcorr <- function (rawmean, 
                     voxcount,
                     background) {
  # subtracts background from every voxel in a volume 
  # uses the mean rather than intden, in order to avoid truncation of sig figs by Volocity 
  (rawmean - background) * voxcount
}

# correcting with intracellular bkgd -----
cell_corr <- bkgcorr(cell_mito_bkd$RawCellMean,
                     cell_mito_bkd$CellVoxelCount,
                     cell_mito_bkd$MeanBackground)

mito_corr <- bkgcorr(cell_mito_bkd$RawMitoMean,
                     cell_mito_bkd$MitoVoxelCount,
                     cell_mito_bkd$MeanBackground)

frac_mito <- mito_corr/cell_corr

corrected_mito_loc <- cell_mito_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)

# Get weighted mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background
mito_mean_corr <- corrected_mito_loc$RawMitoMean - corrected_mito_loc$MeanBackground

corrected_mito_loc <- corrected_mito_loc %>% mutate(MitoMeanCorr = mito_mean_corr)

# correcting with extracellular bkgd -------

cell_corr <- bkgcorr(cell_mito_xc_bkd$RawCellMean,
                     cell_mito_xc_bkd$CellVoxelCount,
                     cell_mito_xc_bkd$ExtracellularBackground)

mito_corr <- bkgcorr(cell_mito_xc_bkd$RawMitoMean,
                     cell_mito_xc_bkd$MitoVoxelCount,
                     cell_mito_xc_bkd$ExtracellularBackground)

frac_mito <- mito_corr/cell_corr
# 
corrected_mito_loc_xc <- cell_mito_xc_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)

# Get weighted mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background
mito_mean_corr <- corrected_mito_loc_xc$RawMitoMean - corrected_mito_loc_xc$ExtracellularBackground

corrected_mito_loc_xc <- corrected_mito_loc_xc %>% mutate(MitoMeanCorr = mito_mean_corr)


# Compare results by temperature and threshold offset ------

# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc$filename, temp_exp)

corrected_mito_loc <- corrected_mito_loc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])


# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc_xc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc_xc$filename, temp_exp)

corrected_mito_loc_xc <- corrected_mito_loc_xc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])


# all data by temp
boxplot(corrected_mito_loc$FractionInMito ~ corrected_mito_loc$Temp, main = "Fraction of GFP in mito, cyto bkgd")

boxplot(corrected_mito_loc_xc$FractionInMito ~ corrected_mito_loc_xc$Temp, main = "Fraction of GFP in mito, xc bkgd")

boxplot(corrected_mito_loc$MitoMeanCorr ~ corrected_mito_loc$Temp, main = "Mean GFP in mito, cyto bkgd")

boxplot(corrected_mito_loc_xc$MitoMeanCorr ~ corrected_mito_loc_xc$Temp, main = "Mean GFP in mito, xc bkgd")

# Compare total cell GFP across temperatures

# is total cellular GFP constant with temp?
boxplot(corrected_mito_loc$CellIntDenCorr ~ corrected_mito_loc$Temp, main = "Total corrected cell GFP, cyto bkgd")

# cell intden vs volume
#plot(corrected_mito_loc$CellIntDenCorr, corrected_mito_loc$CellVolume_um3, main = "Cyto Bkgd")

# is total cellular GFP constant with temp?
boxplot(corrected_mito_loc_xc$CellIntDenCorr ~ corrected_mito_loc_xc$Temp, main = "Total corrected cell GFP, xc bkgd")

# cell intden vs volume
#plot(corrected_mito_loc_xc$CellIntDenCorr, corrected_mito_loc_xc$CellVolume_um3, main = "XC Bkgd")

# TODO: reduce the number of data frames by gradually adding to a single output table

# TODO: Add n to the labels for the plots (for each group)

# Statistical tests -----

permTfrac <- corrected_mito_loc_xc %>% 
  filter(Temp == 25) %>% 
  select(FractionInMito) %>%
  unlist

restrTfrac <- corrected_mito_loc_xc %>% 
  filter(Temp == 36) %>% 
  select(FractionInMito) %>%
  unlist

permTmean <- corrected_mito_loc_xc %>% 
  filter(Temp == 25) %>% 
  select(MitoMeanCorr) %>%
  unlist

restrTmean <- corrected_mito_loc_xc %>% 
  filter(Temp == 36) %>% 
  select(MitoMeanCorr) %>%
  unlist

frac_wilcoxon <- wilcox.test(permTfrac, restrTfrac)
mean_wilcoxon <- wilcox.test(permTmean, restrTmean)

frac_t <- t.test(permTfrac, restrTfrac)
mean_t <- t.test(permTmean, restrTmean)

# Save csv table ------
# overwrites without warning!

outputFile1 = paste(Sys.Date(), "mito_loc.csv") # spaces will be inserted
outputFile2 = paste(Sys.Date(), "mito_loc_xc.csv") # spaces will be inserted

# write_csv(corrected_mito_loc, file.path(here("data"), outputFile1))
# write_csv(corrected_mito_loc_xc, file.path(here("data"), outputFile2))

