# MEN_analysis_2.R
# collect data on mito localization expts

# REQUIRES a dataframe or tibble called df generated by combine_volocity_files.R

# Setup -----
require(dplyr)
require(here)
require(ggplot2)

# 1. Collect background values ---------
# Each file should have exactly 1 background ROI.
# (filter for Population == ROIs, select filename, 470DCI columns)

green_bg <- filter(df, Population == "ROIs") %>%
  select(filename, MeanBackground = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`)


# simple plots
# Most background levels are 650-700
boxplot(green_bg[,2], main = "Deconvolved green channel background")
hist(green_bg[,2] %>% unlist, main="Deconvolved green channel background")


# 2. Collect summarized mito values -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

all_mito <- df %>% filter(Population == "Mito") %>% 
  drop_na(`Compartment Whole cells ID`) %>%        # eliminate mitos not belonging to a cell
  group_by(filename, `Compartment Whole cells ID`) # will sum first by cell

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntden = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            MitoVolume_um3 = sum(`Volume (µm³)`))

  # result has 4 columns

# 3. Collect Whole cell data -------

# uncorrected cell intden, omitting cells with no mito 
raw_cell_intden <- filter(df,
                          Population == "Whole cells" & `Number of contained Mito` != 0) %>%
  select(filename,
         ID,
         RawCellIntDen = `Sum (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellVolume_um3 = `Volume (µm³)`)

# 4. Add columns for mito sum, volume, and background ROI ------

cell_mito_intden <- raw_cell_intden %>% mutate(
  RawMitoIntden = raw_mito_intden$RawMitoIntden,
  MitoVolume_um3 = raw_mito_intden$MitoVolume_um3)

  # note: can insert RawMitoCellID = raw_mito_intden$`Compartment Whole cells ID` to verify that IDs are correct

cell_mito_bkd <- cell_mito_intden %>% left_join(green_bg) # only common column is filename

# 5. Determine background corrected % of green signal in mito ----

#   corr intden = (sum) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size µm3/pixel

voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3

bkgcorr <- function (rawintden, 
                     vol,
                     background,
                     voxsize) {
  # subtracts background from every voxel in a volume 
  rawintden - (background * (vol/voxsize))
}

cell_corr <- bkgcorr(cell_mito_bkd$RawCellIntDen,
                     cell_mito_bkd$CellVolume_um3,
                     cell_mito_bkd$MeanBackground,
                     voxel_size)

mito_corr <- bkgcorr(cell_mito_bkd$RawMitoIntden,
                     cell_mito_bkd$MitoVolume_um3,
                     cell_mito_bkd$MeanBackground,
                     voxel_size)

frac_mito <- mito_corr/cell_corr

corrected_mito_loc <- cell_mito_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)

# 6. filter on temperature ------

# and boxplot the data from #5 

# group by temperature
# TODO: convert this to a factor 

permT <- filter(corrected_mito_loc, grepl("25C", `filename`))
restrT <- filter(corrected_mito_loc, grepl("36C", `filename`))

boxplot(permT$FractionInMito, ylim = c(0,1))
boxplot(restrT$FractionInMito, ylim = c(0,1))


# 7. write a csv file
