# users.R
# R script to process iLab user information
# Theresa Swayne, Columbia University, 2023

# How to use: Run the script. When prompted, open the raw data file (source data CSV generated by iLab). 
# Outputs: Text file with unique user and PI emails separated by the indicated delimiter (default is semicolon; change in Setup section), 
#   and a CSV file with the emails in rows
# Output files will be written to the same directory as the source data


# ---- Setup ----
library(tidyverse)

# delimiter for email lists
# note: for Outlook the delimiter should be ; (semicolon)
delim = ";"

# user chooses a file
ilabfile <- file.choose()
datadir <- dirname(ilabfile)
ilabdata <- read_csv(ilabfile)

# ---- How many individual users are there? ----
# note -- every user has a unique User Login Email

users <- unique(ilabdata$`User Login Email`)
numUsers <- length(users)

# ---- How many PIs? ----

PIs <- unique(ilabdata$`PI Email`)
numPIs <- length(PIs)

# Add the list of PIs to the list of users and eliminate duplicates

allEmails <- c(users, PIs) %>%
  unique()

# remove NAs
allEmails <- allEmails[!is.na(allEmails)]


# ---- Save data ----

# txt format for pasting into outlook
allEmailsDelim <- paste(allEmails, collapse=delim )
txtPath = file.path(datadir, "all_emails.txt")
write(allEmailsDelim, file=txtPath)

# table format for Excel
emailTable <- data.frame(Email=allEmails)
csvPath = file.path(datadir, "all_emails.csv")
write_csv(emailTable, file=csvPath)


